// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlnOVX0K6Io3zI5WyeUst5kC_Ut9vXjJM',
    appId: '1:904363925614:web:ed619c81ae5decf2eb467f',
    messagingSenderId: '904363925614',
    projectId: 'municipal-assets',
    authDomain: 'municipal-assets.firebaseapp.com',
    storageBucket: 'municipal-assets.firebasestorage.app',
    measurementId: 'G-H1BTKCF1J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEBR7jQJG_e4nAQD6uIl-p9VEUjqOseAk',
    appId: '1:904363925614:android:168b9aa19bbaacefeb467f',
    messagingSenderId: '904363925614',
    projectId: 'municipal-assets',
    storageBucket: 'municipal-assets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDurnyVi7cJQnId_KoG3VrC6RiIV1zJBkc',
    appId: '1:904363925614:ios:56433c73f1a0070beb467f',
    messagingSenderId: '904363925614',
    projectId: 'municipal-assets',
    storageBucket: 'municipal-assets.firebasestorage.app',
    iosBundleId: 'com.example.namNagaram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDurnyVi7cJQnId_KoG3VrC6RiIV1zJBkc',
    appId: '1:904363925614:ios:56433c73f1a0070beb467f',
    messagingSenderId: '904363925614',
    projectId: 'municipal-assets',
    storageBucket: 'municipal-assets.firebasestorage.app',
    iosBundleId: 'com.example.namNagaram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlnOVX0K6Io3zI5WyeUst5kC_Ut9vXjJM',
    appId: '1:904363925614:web:6bb42ef62e8a28c2eb467f',
    messagingSenderId: '904363925614',
    projectId: 'municipal-assets',
    authDomain: 'municipal-assets.firebaseapp.com',
    storageBucket: 'municipal-assets.firebasestorage.app',
    measurementId: 'G-4PZ9LHTEH3',
  );

}